# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\tmessenger\"!\n\x0e\x43hannelRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\"A\n\x0b\x43hannelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.messenger.ChannelType\"\x1f\n\x0b\x43hannelList\x12\x10\n\x08\x63hannels\x18\x01 \x03(\t\"2\n\x0eMessageRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty*\'\n\x0b\x43hannelType\x12\t\n\x05UNARY\x10\x00\x12\r\n\tSTREAMING\x10\x01\x32\xd9\x02\n\tMessenger\x12\x37\n\x0bGetChannels\x12\x10.messenger.Empty\x1a\x16.messenger.ChannelList\x12\x43\n\x0eGetChannelInfo\x12\x19.messenger.ChannelRequest\x1a\x16.messenger.ChannelInfo\x12G\n\x0eReceiveMessage\x12\x19.messenger.ChannelRequest\x1a\x1a.messenger.MessageResponse\x12I\n\x0eStreamMessages\x12\x19.messenger.ChannelRequest\x1a\x1a.messenger.MessageResponse0\x01\x12:\n\x0bPostMessage\x12\x19.messenger.MessageRequest\x1a\x10.messenger.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELTYPE']._serialized_start=260
  _globals['_CHANNELTYPE']._serialized_end=299
  _globals['_CHANNELREQUEST']._serialized_start=28
  _globals['_CHANNELREQUEST']._serialized_end=61
  _globals['_CHANNELINFO']._serialized_start=63
  _globals['_CHANNELINFO']._serialized_end=128
  _globals['_CHANNELLIST']._serialized_start=130
  _globals['_CHANNELLIST']._serialized_end=161
  _globals['_MESSAGEREQUEST']._serialized_start=163
  _globals['_MESSAGEREQUEST']._serialized_end=213
  _globals['_MESSAGERESPONSE']._serialized_start=215
  _globals['_MESSAGERESPONSE']._serialized_end=249
  _globals['_EMPTY']._serialized_start=251
  _globals['_EMPTY']._serialized_end=258
  _globals['_MESSENGER']._serialized_start=302
  _globals['_MESSENGER']._serialized_end=647
# @@protoc_insertion_point(module_scope)
